// <auto-generated />
using System;
using DAL.EntityConfig;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(UserProfileDbContext))]
    [Migration("20250927133600_v_1.1AddedIndexInUserCommentTable")]
    partial class v_11AddedIndexInUserCommentTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entities.UserComment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("UserProfileuser_id")
                        .HasColumnType("text");

                    b.Property<DateTime>("added_at")
                        .HasColumnType("DATE");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("event_id")
                        .HasColumnType("integer");

                    b.Property<bool>("is_changed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("rating")
                        .HasColumnType("integer");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("UserProfileuser_id");

                    b.HasIndex("event_id");

                    b.HasIndex("user_id");

                    b.ToTable("UserComment", null, t =>
                        {
                            t.HasCheckConstraint("CK_USER_RATING", "rating >= 0 AND rating <= 5");
                        });
                });

            modelBuilder.Entity("DAL.Entities.UserEventCalendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("UserProfileuser_id")
                        .HasColumnType("text");

                    b.Property<DateTime>("added_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<int>("event_id")
                        .HasColumnType("integer");

                    b.Property<int?>("registration_id")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileuser_id");

                    b.HasIndex("user_id");

                    b.ToTable("UserEventCalendar", null, t =>
                        {
                            t.HasCheckConstraint("CK_STATUS_OF_EVENT", "status IN ('Registered','Interested','Attended')");
                        });
                });

            modelBuilder.Entity("DAL.Entities.UserProfile", b =>
                {
                    b.Property<string>("user_id")
                        .HasColumnType("text");

                    b.Property<string>("bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("birth_date")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("user_id");

                    b.HasIndex("user_id")
                        .IsUnique();

                    b.ToTable("UserProfile", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.UserComment", b =>
                {
                    b.HasOne("DAL.Entities.UserProfile", null)
                        .WithMany("Comments")
                        .HasForeignKey("UserProfileuser_id");
                });

            modelBuilder.Entity("DAL.Entities.UserEventCalendar", b =>
                {
                    b.HasOne("DAL.Entities.UserProfile", null)
                        .WithMany("EventCalendar")
                        .HasForeignKey("UserProfileuser_id");
                });

            modelBuilder.Entity("DAL.Entities.UserProfile", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("EventCalendar");
                });
#pragma warning restore 612, 618
        }
    }
}
